// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1bf44059-76d8-4589-bc48-e290d7f04a60",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_Bjmq09nb0",
    "aws_user_pools_web_client_id": "723bb0j995kt6odn4bj9oc8vbt",
    "oauth": {}
};


export default awsmobile;
